# Generated by Django 2.2.5 on 2020-01-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0003_auto_20191102_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
    ]
